--[[
postgres.

`pg_catalog` answers rather than `information_schema`, because `relkind` sorts
tables, views, materialized views and partitioned tables in one pass, and
because the `pg_get_*def` functions hand back the definition text the standard
views do not carry.

A connection reaches one database, so the catalog level lists the others on the
same server and each one carries its own url. Nothing below a catalog crosses
into another, which is what postgres allows rather than a choice made here.

One catalog is one query, so an object the connected role cannot read fails the
whole catalog rather than going missing from it. A permission error naming the
object is the better of the two, because a tree quietly missing a table is a
tree that cannot be trusted.
]]

local quote = require("neo-tree-database.quote")
local queries = require("neo-tree-database.schemes.postgres.sql")
local url = require("neo-tree-database.url")

local M = {}

M.quoting = quote.ANSI

--- psql prints the one value and nothing else: no alignment, no header, no
--- pager, and no psqlrc that could turn any of those back on.
---@param connection string
---@param sql string
---@return dbtree.Request
local function invoke(connection, sql)
  return {
    argv = { "psql", connection, "-X", "-q", "-A", "-t", "-v", "ON_ERROR_STOP=1", "-c", sql },
  }
end

--- Each database on the server is its own connection, because postgres cannot
--- query across one.
---@param connection string
---@param catalog string
---@return string
function M.catalog_url(connection, catalog)
  return url.with_database(connection, catalog)
end

---@param connection string
---@return dbtree.Request
function M.catalogs(connection)
  return invoke(connection, queries.CATALOGS)
end

--- The catalog is reached by connecting to it, so the query names no database
--- and carries nothing from the tree into sql.
---@param catalog_url string
---@param catalog string
---@return dbtree.Request
function M.introspect(catalog_url, catalog)
  return invoke(catalog_url, queries.INTROSPECT)
end

--- The name db-query's catalog knows a relation by. The catalog is the
--- database the url connects to, so the name starts at the schema.
---@param catalog string
---@param schema string
---@param relation string
---@return string[]
function M.catalog_name(catalog, schema, relation)
  return { schema, relation }
end

--- How a column states where its value comes from. An identity column and a
--- generated column both keep their expression where a default would go, and
--- writing that expression out as a DEFAULT would describe a column that
--- accepts writes when the real one does not.
---@param column dbtree.Column
---@return string
local function column_source(column)
  if column.generated == "s" then
    return " GENERATED ALWAYS AS (" .. (column.default or "") .. ") STORED"
  end
  if column.identity == "a" then
    return " GENERATED ALWAYS AS IDENTITY"
  end
  if column.identity == "d" then
    return " GENERATED BY DEFAULT AS IDENTITY"
  end
  if column.default then
    return " DEFAULT " .. column.default
  end
  return ""
end

--- How `column` reads inside a CREATE TABLE or after an ADD COLUMN.
---@param column dbtree.Column
---@return string
function M.column_definition(column)
  local text = quote.identifier(column.name, M.quoting) .. " " .. (column.type or "")
  text = text .. column_source(column)
  if not column.nullable then
    text = text .. " NOT NULL"
  end
  return text
end

--- Postgres keeps no `CREATE TABLE` text, so a table's statement is rebuilt
--- from the columns and constraints the catalog fetch already returned. A view
--- carries its own definition and is handed back as it came.
---@param relation dbtree.Relation
---@param schema string
---@return string[]
function M.ddl(relation, schema)
  if relation.definition then
    return vim.split(relation.definition, "\n", { plain = true })
  end

  local parts = {}
  for _, column in ipairs(relation.columns or {}) do
    table.insert(parts, M.column_definition(column))
  end
  for _, constraint in ipairs(relation.constraints or {}) do
    if constraint.definition then
      table.insert(
        parts,
        "CONSTRAINT "
          .. quote.identifier(constraint.name, M.quoting)
          .. " "
          .. constraint.definition
      )
    end
  end

  local lines = { "CREATE TABLE " .. quote.qualified(schema, relation.name, M.quoting) .. " (" }
  for index, part in ipairs(parts) do
    table.insert(lines, "    " .. part .. (index < #parts and "," or ""))
  end
  table.insert(lines, ");")

  -- The index behind a primary key or a unique constraint is already stated by
  -- the constraint above, and repeating it as a CREATE INDEX would make the
  -- statement fail against an empty database.
  for _, index in ipairs(relation.indexes or {}) do
    if index.definition and not index.owned_by_constraint then
      table.insert(lines, "")
      table.insert(lines, index.definition .. ";")
    end
  end

  return lines
end

return M
